export const helpCfg = {
  title: 'Sky菜单',
  subTitle: 'Yunzai-Bot & Tlon-Sky',
  columnCount: 0,
  colWidth: 265,
  theme: 'all',
  themeExclude: ['default'],
}
export const helpList = [{
    "group": "每日功能",
    "auth": false,
    "list": [{
        "icon": 1,
        "title": "#今日任务",
        "desc": "查看国服今日任务"
      }, {
        "icon": 11,
        "title": "#季蜡位置",
        "desc": "查看今日季蜡具体位置"
      }, {
        "icon": 21,
        "title": "#大蜡位置",
        "desc": "查看今日大蜡具体位置"
      }, {
        "icon": 31,
        "title": "#今日魔法",
        "desc": "查看今日免费魔法"
      }, {
        "icon": 41,
        "title": "#光遇签到",
        "desc": "咕咕咕中..."
      }]
  }, {
    "group": "查询功能",
    "list": [{
        "icon": 2,
        "title": "#Sky状态",
        "desc": "查询光遇是否炸服"
      }, {
        "icon": 12,
        "title": "#白蜡查询 #季蜡查询",
        "desc": "查询最近蜡烛变化"
      }, {
        "icon": 22,
        "title": "#季节剩余 #活动剩余",
        "desc": "查询剩余时间"
      }, {
        "icon": 32,
        "title": "#往期复刻",
        "desc": "查看往期复刻"
      }, {
        "icon": 42,
        "title": "#(季节名)季多久未复刻",
        "desc": "查询季节先祖多久未复刻"
      }, {
        "icon": 26,
        "title": "#上传角色",
        "desc": "获取绑定光遇id所需的id"
      }, {
        "icon": 36,
        "title": "#绑定光遇id #查询光遇id",
        "desc": "绑定和查询光遇id"
      }]
  }, {
    "group": "身高查询功能",
    "list": [{
      "icon": 100,
      "title": "填写身高密钥",
      "desc": "填写您所购买的密钥"
    }, {
      "icon": 100,
      "title": "获取密钥",
      "desc": "获取查询身高密钥"
    }, {
      "icon": 100,
      "title": "查询身高密钥",
      "desc": "查询您所填写的密钥"
    }, {
      "icon": 100,
      "title": "绑定身高id",
      "desc": "绑定您的光遇ID"
    }, {
      "icon": 100,
      "title": "查询身高",
      "desc": "查询您的身高数值" 
    }]
  }, {
    "group": "兑换图功能",
    "list": [{
        "icon": 3,
        "title": "#常驻兑换图",
        "desc": "查看常驻兑换图列表"
      }, {
        "icon": 13,
        "title": "#季节兑换图",
        "desc": "查看季节兑换图列表"
      }, {
        "icon": 23,
        "title": "#活动兑换图",
        "desc": "查看活动兑换图列表"
      }, {
        "icon": 33,
        "title": "#复刻兑换图",
        "desc": "查看最近一次复刻的兑换图"
      }, {
        "icon": 43,
        "title": "#好友树兑换图",
        "desc": "查看好友树解锁图"
      }]
  }, {
    "group": "娱乐功能",
    "list": [{
        "icon": 6,
        "title": "#复刻预测",
        "desc": "随机两位复刻先祖"
      }, {
        "icon": 16,
        "title": "#绘画分享",
        "desc": "光遇同人赏析"
      }, {
        "icon": 46,
        "title": "#光遇签到",
        "desc": "签到获得每日蜡烛(假"
      }]
  }, {
    "group": "其他功能",
    "list": [{
        "icon": 4,
        "title": "#蜡烛合成机制",
        "desc": "蜡烛合成讲解"
      }, {
        "icon": 14,
        "title": "#测量规则",
        "desc": "身高测量规则"
      }, {
        "icon": 24,
        "title": "#身高进阶知识",
        "desc": "对身高的各种讲解"
      }, {
        "icon": 34,
        "title": "#身高透明图",
        "desc": "身高对比图透明背景版"
      }, {
        "icon": 44,
        "title": "#身高图",
        "desc": "获取身高对比查询图片"
      }]
  }, {
    "group": "版权说明：图片源自网络，如有侵权·联系删除",
    "list": []
  }]