export const helpCfg = {
  title: 'Sky菜单',
  subTitle: 'Tlon-Sky',
  columnCount: 0,
  colWidth: 265,
  theme: 'all',
  themeExclude: ['default'],
}
export const helpList = [{
  "group": "每日功能",
  "auth": false,
  "list": [{
    "icon": 21,
    "title": "#今日任务",
    "desc": "查看国服今日任务丨季蜡丨大蜡等"
  }, {
    "icon": 31,
    "title": "#代币位置",
    "desc": "查看国服今日获取代币位置"
  }, {
    "icon": 41,
    "title": "#季节任务",
    "desc": "查看国服当前季节任务"
  }]
}, {
  "group": "查询功能",
  "list": [{
    "icon": 51,
    "title": "#Sky状态",
    "desc": "查询光遇是否炸服"
  }, {
    "icon": 61,
    "title": "#光遇公告",
    "desc": "查看告示栏内容"
  }, {
    "icon": 71,
    "title": "#季节剩余",
    "desc": "季节相关内容计算"
  }, {
    "icon": 81,
    "title": "24年复刻记录",
    "desc": "查看往期复刻记录可选[20,21,22,23]"
  }, {
    "icon": 91,
    "title": "#风行季多久未复刻",
    "desc": "查询季节先祖多久未复刻[可选其他季节]"
  }, {
    "icon": 101,
    "title": "#全图鉴参考",
    "desc": "衣柜图鉴参考[国际服版]"
  }, {
    "icon": 25,
    "title": "光翼统计",
    "desc": "光翼数量统计"
  }, {
    "icon": 14,
    "title": "碎石查询",
    "desc": "光遇碎石信息查询"
  }]
}, {
  "group": "兑换图功能",
  "list": [{
    "icon": 111,
    "title": "#常驻兑换图列表",
    "desc": "查看常驻兑换图"
  }, {
    "icon": 22,
    "title": "#季节兑换图列表",
    "desc": "查看季节兑换图"
  }, {
    "icon": 32,
    "title": "#复刻兑换图",
    "desc": "查看最近一次复刻的兑换图"
  }, {
    "icon": 42,
    "title": "#好友树兑换图",
    "desc": "查看好友树解锁图"
  }]
}, {
  "group": "娱乐功能",
  "list": [{
    "icon": 52,
    "title": "#复刻预测",
    "desc": "随机两位复刻先祖"
  }, {
    "icon": 62,
    "title": "#绘画分享",
    "desc": "光遇同人赏析"
  }, {
    "icon": 72,
    "title": "#Sky娱乐菜单",
    "desc": "查看蜡烛娱乐功能"
  }]
}, {
  "group": "其他功能",
  "list": [{
    "icon": 82,
    "title": "#蜡烛合成机制",
    "desc": "蜡烛合成讲解"
  }, {
    "icon": 92,
    "title": "#测量规则",
    "desc": "身高测量规则"
  }, {
    "icon": 102,
    "title": "#身高进阶知识",
    "desc": "对身高的各种讲解"
  }, {
    "icon": 112,
    "title": "#身高透明图",
    "desc": "身高对比图透明背景版"
  }, {
    "icon": 23,
    "title": "#身高图",
    "desc": "获取身高对比查询图片"
  }]
}, {
  "group": "版权说明：图片源自网络，如有侵权·联系删除",
  "list": []
}]